---
- name: My test playbook
  hosts: all
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: start apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache package
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copying indexfile
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0777
